name: twidgets
description: "A package with basic interface elements highly customizable."
version: 0.0.1
homepage: www.torugo.com.br

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
# flutter:
