name: twidgets
description: "A package with basic interface elements highly customizable."
version: 0.0.1
homepage: www.torugo.com.br

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: EyeIcons
      fonts:
        - asset: lib/fonts/EyeIcons.ttf
          weight: 400
